In [ ]:
# 1. 넘파이 기초

# 일반 리스트
list_data = [1,2,3,4,5]
print(list_data)
type(list_data)

[1, 2, 3, 4, 5]


list

In [ ]:
import numpy as np # numpy를 불러오고 사용할때는 np라는 별칭으로 사용
array_data = np.array(list_data)
#
print(array_data)
type(array_data)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# 리스트와 배열의 연산 비교

# 리스트의 데이터는 사칙연산을 하면 데이터가 합쳐진다.
list_a = [1,2,3]
list_b = [4,5,6]
print(list_a + list_b)

[1, 2, 3, 4, 5, 6]


In [ ]:
# 넘파이 배열에서는 같은 위치에 있는 데이터가 서로 연산이 가능해진다.

arr_a = np.array(list_a)
arr_b = np.array(list_b)
print(arr_a + arr_b)

[5 7 9]


In [ ]:
# 배열 생성 방법

# 1. 1차원
arr_1 = np.array([1,2,3])

# 2. 2차원
arr_2 = np.array([
                  [1,2,3],
                  [4,5,6]
                  ]) # 2차원 배열(행, 열)

print(arr_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 0으로만 된 배열 생성
a = np.zeros(5)
print(a)
# Start, stop, step형식으로 자료 생성
b = np.arange(1, 10, 2)
print(b)
# 0과 1사이의 난수 생성 - 3개
c = np.random.rand(3)
print(c)

[0. 0. 0. 0. 0.]
[1 3 5 7 9]
[0.49309058 0.97597051 0.3134538 ]


In [ ]:
# 배열에 대한 속성 확인

# arr_2에 대한 정보!
# 데이터가 아주 큰 경우

print("차원", arr_2.ndim)
print("크기", arr_2.shape)
print("원소 개수", arr_2.size)
print("데이터 타입", arr_2.dtype)

차원 2
크기 (2, 3)
원소 개수 6
데이터 타입 int64


In [ ]:
# arr_1을 활용한 넘파이 연산
# 전체 배열에 덧셈이 되는 것을 알 수 있다.
# 브로드캐스팅

print("덧셈", arr_1+5)
print("뺄셈", arr_1-5)
print("곱셈", arr_1*5)
print("나눗셈", arr_1/5) # 결과가 소수형으로 변경
print("평균", np.mean(arr_1))
print("표준편차", np.std(arr_1))

덧셈 [6 7 8]
뺄셈 [-4 -3 -2]
곱셈 [ 5 10 15]
나눗셈 [0.2 0.4 0.6]
평균 2.0
표준편차 0.816496580927726


In [ ]:
# 실습 아이디어 단어 길이 통계 분석기

# 단어 5개
# 6 / 4 / 2 / 7 / 8

# numpy는 수치계산에 용이하기 때문에 문자에 대한 데이터는 숫자로 변경한 뒤에 처리가 필요!
words = ['python', 'data', 'Ai', 'machine', 'learning']

# 반복문을 한줄로 간단하게 표현하는 방법
# 리스트 컴프리핸션 리스트안에 반복문이나 조건문 연산을 바로 하는 구문
# np.array에는 리스트가 들어가서 배열로 변환
lengths = np.array([len(w) for w in words])
print(lengths)
print(np.mean(lengths))


[6 4 2 7 8]
5.4


In [ ]:
import numpy as np

# 1차원 배열 생성
arr = np.array([10, 20, 30, 40, 50])
print("배열:", arr)

# 인덱싱
print("첫 번째 요소:", arr[0])
print("마지막 요소:", arr[-1])

# 수정
arr[2] = 99
print("수정 후 배열:", arr)

배열: [10 20 30 40 50]
첫 번째 요소: 10
마지막 요소: 50
수정 후 배열: [10 20 99 40 50]


In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
arr2[1,2]

np.int64(6)

In [ ]:
# array3는 1차원 배열의 변수 이름
array3 = np.array([10,20,30,40,50])

In [ ]:
# 기본 통계 함수
print(np.sum(array3)) # 합계
print(np.mean(array3)) # 평균
print(np.max(array3)) # 최대값
print(np.min(array3)) # 최소값
print(np.std(array3)) # 표준편차

150
30.0
50
10
14.142135623730951


In [ ]:
# 로또 당첨 번호 생성기
# 복원 추출
lotto = np.random.randint(1, 46, size = 6)
print(lotto)
# array() ()괄호 안에에는 리스트가 있죠
# 리스트에는 콤마가 있고, array로 출력하면 콤마가 없습니다.

[21 31 22 33  8  4]


In [ ]:
# 겹치지 않는 로또 당첨 번호 생성기
# 비복원 추출
lotto = np.random.choice(range(1,46), size=6, replace=False)
lotto.sort() # 데이터 오름차순 정렬
print(lotto)

[11 14 15 18 23 24]


In [ ]:
# 판다스 1차원 자료 생성 - 시리즈(series)

import pandas as pd

# 1차원 판다스 시리즈 생성 - 출력결과는 엑셀의 세로 열이 보여지는 것과 동일하게 출력된다.
# index는 자동으로 생성 된다. 만약 index를 변경하고 싶으면 데이터에 맞게 구조를 일치해서 변경하면 된다.
s = pd.Series([100,200,300,400], index =['A','B','C','D'])
print(s)
type(s)

A    100
B    200
C    300
D    400
dtype: int64


pandas.core.series.Series

In [ ]:
# DataFrame 2차원 배열(자료) 생성
# 딕셔너리, json형태의 자료구조형태를 볼 수 있다.
# 또는 CSV, Json 이러한 기존 자료구조 형태가 있으면 그 파일을 그대로 적용할 수 있다.

data = {
    "이름" : ['홍길동', '이몽룡', '성춘향'],
    "나이" : [30,25,22],
    "직업" : ["개발자", "기획자", "디자이너"]
}

df = pd.DataFrame(data)
print(data)
print(df)

{'이름': ['홍길동', '이몽룡', '성춘향'], '나이': [30, 25, 22], '직업': ['개발자', '기획자', '디자이너']}
    이름  나이    직업
0  홍길동  30   개발자
1  이몽룡  25   기획자
2  성춘향  22  디자이너


In [ ]:
# 데이터프레임을 csv파일로 저장하기
df.to_csv("test.csv", index=False, encoding='utf-8')

In [ ]:
# 외부의 csv파일을 읽어오기 -> 데이터프레임으로 변환
df2 = pd.read_csv('test.csv', encoding='utf-8')
print(df2)

    이름  나이    직업
0  홍길동  30   개발자
1  이몽룡  25   기획자
2  성춘향  22  디자이너


In [ ]:
# 데이터 확인 메서드 - 데이터를 외부에서 읽었을때 또는 생성했을때 가장 먼저 해야하는 3가지
# 1. head() - 상위 5개의 자료를 보는 방법
# 1. tail() - 하위 5개의 자료를 보는 방법

# 1) 데이터가 제대로 출력이 되는지 여부를 파악 - 만약에 인코딩이나 기타 한글인식이 제대로 되지 않으면 특수문자처럼 보여지거나
# 자료가 밀리는 현상이 발생

print(df2.head())
print(df2.tail())

# 2. info()
# range index - 3 entries -> 총 데이터의 갯수를 파악 (행 파악)
# Data columns - total 3 columns -> 총 자료의 갯수를 파악(열 파악)
# Non-Null Count - 결측치가 얼마나 있는지 여부를 파악
# Dtype - 데이터의 자료구조가 숫자, 문자형, 소수형, 불린, 날짜
# memory usage - 데이터를 읽었을때 시간이 얼마나 걸리고, 내 컴퓨터에서 감당 가능한 자료인지?

print(df2.info())

# 3. describe()

# 통계량을 확인하는 문법 - 수치형자료에 대해서만 통계량을 확인할 수 있음
# 1. 이상치는 없는지 - 너무 값이나 너무 작은 값 또는 9999999 8888888 특이한 값은 없는지
# 2. 평균 / 중앙값 / 표준편차 -> 데이터의 구조 / 분포 등을 확인
# 3. 한가지값으로만 이루어지지 않았는지 빠르게 파악 min 0 25% 0 50% 0 75% 0 100% 0 -> 모든 자료가 0 -> 의미가 없음

print(df2.describe())

    이름  나이    직업
0  홍길동  30   개발자
1  이몽룡  25   기획자
2  성춘향  22  디자이너
    이름  나이    직업
0  홍길동  30   개발자
1  이몽룡  25   기획자
2  성춘향  22  디자이너
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      3 non-null      object
 1   나이      3 non-null      int64 
 2   직업      3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
              나이
count   3.000000
mean   25.666667
std     4.041452
min    22.000000
25%    23.500000
50%    25.000000
75%    27.500000
max    30.000000


In [ ]:
df = 1
df = 2
print(df)

2


In [ ]:
import pandas as pd

data = {
    "이름" : ['홍길동', '이몽룡', '성춘향'],
    "부서" : ['개발', '기획', '디자인'],
    "직급" : ["대리", "사원", "과장"],
    "연봉" : [5500, 4200, 6000]
}

df = pd.DataFrame(data)
df.to_csv("users.csv", index=False, encoding='utf-8')

df = pd.read_csv("users.csv", encoding="utf-8")
# print(df)

print("데이터 상위:")
print(df.head(2))

print("평균 연봉:", df["연봉"].mean())
print("최고 연봉:", df["연봉"].max())

데이터 상위:
    이름  부서  직급    연봉
0  홍길동  개발  대리  5500
1  이몽룡  기획  사원  4200
평균 연봉: 5233.333333333333
최고 연봉: 6000


In [ ]:
# 판다스는 시리즈로 계산이 된다.

In [ ]:
print(df) # 데이터 프레임
print('------')
print(df['연봉']) # 인덱싱을 활용하면 열자료의 모든 것을 가져올수 있음 -> 시리즈
print('------')
print(df['연봉'].mean())
print('------')
# 2차원으로 원하는 열만 출력하고 싶을때는 [[]] 대괄호를 두개를 써서 새로운 데이터 프레임을 만든다.
print(df[['연봉','직급']])

    이름   부서  직급    연봉
0  홍길동   개발  대리  5500
1  이몽룡   기획  사원  4200
2  성춘향  디자인  과장  6000
------
0    5500
1    4200
2    6000
Name: 연봉, dtype: int64
------
5233.333333333333
------
     연봉  직급
0  5500  대리
1  4200  사원
2  6000  과장


In [ ]:
# csv파일 불러오기
df = pd.read_csv("news_data.csv", encoding = "utf-8")

In [ ]:
print(df)

                title       source        date
0  ChatGPT, 새로운 기능 발표  OpenAI Blog  2025-10-01
1   삼성전자, AI 사업 강화 발표         조선일보  2025-10-01
2  LG전자, 로봇 신제품 출시 계획         중앙일보  2025-10-02
3  네이버, 클라우드 시장 확대 추진          한겨레  2025-10-03
4   카카오, AI 번역 서비스 공개        머니투데이  2025-10-03


In [ ]:
print(df.info())

# 고유값 - 고유한 값 -> 5, 5, 4,4, 3,2,1 -> 중복을 제거
# 5,4,3,2,1 -> 고유값
# 최빈값 -> 최대 빈도를 차지하고 있는 값
print(df.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   5 non-null      object
 1   source  5 non-null      object
 2   date    5 non-null      object
dtypes: object(3)
memory usage: 252.0+ bytes
None
                     title       source        date
count                    5            5           5
unique                   5            5           3
top     ChatGPT, 새로운 기능 발표  OpenAI Blog  2025-10-01
freq                     1            1           2


In [ ]:
# 텍스트 컬럼을 다룰때 판다스에서 잊지 말아야할 접근자 str
df['title_lower'] = df['title'].str.lower()
print(df)
# 만약 title title_lower
print(df[['title','title_lower']])

                title       source        date         title_lower
0  ChatGPT, 새로운 기능 발표  OpenAI Blog  2025-10-01  chatgpt, 새로운 기능 발표
1   삼성전자, AI 사업 강화 발표         조선일보  2025-10-01   삼성전자, ai 사업 강화 발표
2  LG전자, 로봇 신제품 출시 계획         중앙일보  2025-10-02  lg전자, 로봇 신제품 출시 계획
3  네이버, 클라우드 시장 확대 추진          한겨레  2025-10-03  네이버, 클라우드 시장 확대 추진
4   카카오, AI 번역 서비스 공개        머니투데이  2025-10-03   카카오, ai 번역 서비스 공개
                title         title_lower
0  ChatGPT, 새로운 기능 발표  chatgpt, 새로운 기능 발표
1   삼성전자, AI 사업 강화 발표   삼성전자, ai 사업 강화 발표
2  LG전자, 로봇 신제품 출시 계획  lg전자, 로봇 신제품 출시 계획
3  네이버, 클라우드 시장 확대 추진  네이버, 클라우드 시장 확대 추진
4   카카오, AI 번역 서비스 공개   카카오, ai 번역 서비스 공개


In [ ]:
# 특정 단어가 포함된 여부 필터링

# AI라는 단어가 들어간 뉴스만 추출
# 필터링

# 기본 필터링
# 데이터프레임명[ 조건식 ] -> 원하는 데이터만 가져온다.
# 조건식은 데이터프레임의 특정한 시리즈에 대해서 조건을 걸면 된다.

# df[df['title'] == 'ChatGPT, 새로운 기능 발표']

# AI가 들어간 뉴스에 대해서 추출
# contains를 활용하면 특정단어가 들어간 문장을 쉽게 찾을수 있다.
df[df['title'].str.contains("AI")]

title source        date        title_lower
1  삼성전자, AI 사업 강화 발표   조선일보  2025-10-01  삼성전자, ai 사업 강화 발표
4  카카오, AI 번역 서비스 공개  머니투데이  2025-10-03  카카오, ai 번역 서비스 공개

In [ ]:
# ,를 -으로 바꾸는 텍스트 처리
# 특수문자는 보통 텍스트 분석을 할때 제외를 하거나 변경을 하는 상황

# replace(기존 값 , 새로운 값)
df['title'].str.replace(',', ' -')

# 문장의 길이를 파악 len()
df['title'].str.len()

0    18
1    17
2    18
3    18
4    17
Name: title, dtype: int64

In [ ]:
import pandas as pd

# 1️⃣ 데이터 불러오기
# news_data.csv로 변환해서 진행
df = pd.read_csv("news_data.csv", encoding="utf-8")

# 2️⃣ 텍스트 정제 # 만약 정규표현식을 사용할 거라면 regex = True
df["title_clean"] = df["title"].str.replace(",", "", regex=False).str.strip()

# 3️⃣ 키워드 필터링
# case=False는 대소문자를 무시하고 검색
# na=False는 NaN 값에 대해서 포함 안함
ai_news = df[df["title_clean"].str.contains("AI", case=False, na=False)]
chatgpt_news = df[df["title_clean"].str.contains("ChatGPT", case=False, na=False)]

# 4️⃣ 길이 계산
df["length"] = df["title_clean"].str.len()
avg_len = df["length"].mean()

# 5️⃣ 결과 저장
df.to_csv("news_cleaned.csv", index=False, encoding="utf-8")

# 출력
print("✅ 정제된 뉴스 데이터 저장 완료 (news_cleaned.csv)")
print(f"전체 평균 제목 길이: {avg_len:.1f}자")
print(f"AI 관련 뉴스 개수: {len(ai_news)}건 / ChatGPT 관련: {len(chatgpt_news)}건")


✅ 정제된 뉴스 데이터 저장 완료 (news_cleaned.csv)
전체 평균 제목 길이: 16.6자
AI 관련 뉴스 개수: 2건 / ChatGPT 관련: 1건


In [ ]:
df = pd.DataFrame({
    "title" : [
        "    ChatGPT, AI 혁신", # 앞에만 공백 있음
        "카카오 AI 번역",         # 일반 문장
        None,                  # 데이터 없음
        "    LG 전자 로봇 출시   " # 앞뒤 공백 있음
    ]
})

In [ ]:
print(df)

                title
0      ChatGPT, AI 혁신
1           카카오 AI 번역
2                None
3      LG 전자 로봇 출시   


함수	설명	예시
* str.lower()	소문자로 변환	"HELLO" → "hello"
* str.upper()	대문자로 변환	"hello" → "HELLO"
* str.strip()	좌우 공백 제거	"  hi  " → "hi"
* str.replace(a, b)	특정 문자열 대체	"AI, 혁신" → "AI 혁신"
* str.contains("단어")	특정 단어 포함 여부 확인	True/False
* str.len()	문자열 길이 계산	"AI" → 2
* str.split("구분자")	문자열 분리	"A-B-C" → ["A","B","C"]

In [ ]:
# 기본 문자열 변환
# 공백 제거 / 점, !, - 구두점 제거 / 대소문자 -> 하나로 통일 / 기타 값 대체

# title 에 대해서 . 공백제거 . , 을 공백으로 대체 . 소문자 변환
df['title_clean'] = df['title'].str.strip().str.replace(',','').str.lower()

In [ ]:
print(df)

                title    title_clean
0      ChatGPT, AI 혁신  chatgpt ai 혁신
1           카카오 AI 번역      카카오 ai 번역
2                None           None
3      LG 전자 로봇 출시       lg 전자 로봇 출시


In [ ]:
# 결측치 처리
# 결측치 처리하는 이유?
# 결측치가 있으면 향후 머신러닝/딥러닝 모델에서는 계산값이 잘못되거나 오류가 날 가능성이 커지기 때문
# 결측치가 값의 왜곡을 줄 수 있기 때문에

# isnull - 결측치가 있는지 없는지 확인(True/False)
# fillna - na를 특정값으로 대체
# dropna - na를 제거

print(df.isnull()) # 결측치가 있는지 없는지 확인
# title에 결측치가 전체 몇개가 있는지 확인? -> sum() True = 숫자 1과 동일
print(df.isnull().sum())

# 결측치를 대체 -> 결측치를 fillna를 통해 fillna()안에 넣은 값으로 결측치를 대체
df['title_fill'] = df['title'].fillna("여기에는 정보가 없습니다.")
print(df)

# 결측치를 제거 후 자료가 있는 행만 남긴다. -> 결측치 None Na NaN 공백
# (파이썬이 결측치라고 생각하는 데이터에 대해서 처리)
df_drop = df.dropna() # 결측치가 있는 모든 행을 제거
print(df_drop)

df_drop_2 = df.dropna(subset=['title_fill'])
print(df_drop_2)



   title  title_clean  title_fill
0  False        False       False
1  False        False       False
2   True         True       False
3  False        False       False
title          1
title_clean    1
title_fill     0
dtype: int64
                title    title_clean          title_fill
0      ChatGPT, AI 혁신  chatgpt ai 혁신      ChatGPT, AI 혁신
1           카카오 AI 번역      카카오 ai 번역           카카오 AI 번역
2                None           None      여기에는 정보가 없습니다.
3      LG 전자 로봇 출시       lg 전자 로봇 출시      LG 전자 로봇 출시   
                title    title_clean          title_fill
0      ChatGPT, AI 혁신  chatgpt ai 혁신      ChatGPT, AI 혁신
1           카카오 AI 번역      카카오 ai 번역           카카오 AI 번역
3      LG 전자 로봇 출시       lg 전자 로봇 출시      LG 전자 로봇 출시   
                title    title_clean          title_fill
0      ChatGPT, AI 혁신  chatgpt ai 혁신      ChatGPT, AI 혁신
1           카카오 AI 번역      카카오 ai 번역           카카오 AI 번역
2                None           None      여기에는 정보가 없습니다.
3      LG 전자 로봇 출시       

In [ ]:
import pandas as pd

# 샘플 리뷰 데이터 생성 (또는 review.csv 불러오기)
data = {
    "review": [
        "너무 좋아요! 제품 퀄리티 👍",
        "배송이 느려요...ㅠㅠ",
        "가격이 저렴하고 품질도 만족합니다!",
        "재구매 의사 100% 있습니다!!!",
        "별로예요. 다시는 안 살 듯😢"
    ]
}

df = pd.DataFrame(data)
print("📦 원본 리뷰 데이터:")
print(df)

📦 원본 리뷰 데이터:
                review
0     너무 좋아요! 제품 퀄리티 👍
1         배송이 느려요...ㅠㅠ
2  가격이 저렴하고 품질도 만족합니다!
3  재구매 의사 100% 있습니다!!!
4     별로예요. 다시는 안 살 듯😢


In [ ]:
# 정규표현식 전용 라이브러리 re
import re

# 특수문자에 대해서 제거!
# 한글, 영문, 숫자, 공백정도만 남기고 나머지는 다 제거

# 1. 특수문자를 모두 제거
# ^ -> 부정(not)
# ㄱ-ㅎ 한글의 자모
# 가-힝 한글의 전체 문자
# a-z 영소문자
# A-Z 영대문자
# 0-9 숫자
# " " 공백
# -> 한글, 영문자, 숫자, 공백을 제외한 나머지는 모두 => ""로 대체해라
df['clean_review'] = df['review'].str.replace("[^ㄱ-ㅎ가-힣a-zA-Z0-9 ]", "", regex=True)
df['clean_review_1'] = df['clean_review'].str.strip()

print(df[['review','clean_review']])

                review        clean_review
0     너무 좋아요! 제품 퀄리티 👍      너무 좋아요 제품 퀄리티 
1         배송이 느려요...ㅠㅠ             배송이 느려요
2  가격이 저렴하고 품질도 만족합니다!  가격이 저렴하고 품질도 만족합니다
3  재구매 의사 100% 있습니다!!!     재구매 의사 100 있습니다
4     별로예요. 다시는 안 살 듯😢      별로예요 다시는 안 살 듯


In [ ]:
df['review'].str.len()

0    16
1    12
2    19
3    19
4    16
Name: review, dtype: int64

In [ ]:
df['clean_review'].str.len()

0    14
1     7
2    18
3    15
4    14
Name: clean_review, dtype: int64

In [ ]:
# 긍정 / 부정에 대한 리뷰를 찾는데 -> 긍정에 해당하는 용어들 / 부정에 해당하는 용어들을
# |(파이프)를 통해서 비교조건문 or과 동일한 역할 -> 다양한 필터링이 가능해진다.

positive = df[df['clean_review'].str.contains("좋아요|만족합니다")]
negative = df[df['clean_review'].str.contains("별로|느려요")]

print(positive)
print(negative)

                review        clean_review      clean_review_1
0     너무 좋아요! 제품 퀄리티 👍      너무 좋아요 제품 퀄리티        너무 좋아요 제품 퀄리티
2  가격이 저렴하고 품질도 만족합니다!  가격이 저렴하고 품질도 만족합니다  가격이 저렴하고 품질도 만족합니다
             review    clean_review  clean_review_1
1      배송이 느려요...ㅠㅠ         배송이 느려요         배송이 느려요
4  별로예요. 다시는 안 살 듯😢  별로예요 다시는 안 살 듯  별로예요 다시는 안 살 듯


In [ ]:
# 판다스 그룹화 분석

In [ ]:
import pandas as pd

data = {
    "부서": ["개발", "개발", "기획", "디자인", "기획", "디자인"],
    "직원": ["홍길동", "이몽룡", "성춘향", "변학도", "방자", "춘향이"],
    "연봉": [6000, 5500, 4800, 5200, 4500, 5300]
}

df = pd.DataFrame(data)
print(df)


    부서   직원    연봉
0   개발  홍길동  6000
1   개발  이몽룡  5500
2   기획  성춘향  4800
3  디자인  변학도  5200
4   기획   방자  4500
5  디자인  춘향이  5300


In [ ]:
# 1가지 값(평균값)에 대해서 그룹화 분석을 진행
# 데이터프레임.groupby(카테고리이름)[계산할 값].계산방법메서드
result = df.groupby("부서")['연봉'].mean()
print(result)

부서
개발     5750.0
기획     4650.0
디자인    5250.0
Name: 연봉, dtype: float64


In [ ]:
# 자료의 정렬이 필요하다. sort_values
# 만약에 내림차순으로 정렬이 필요하다. -> (ascending=False) / 아무것도 안쓰거나 True 오름차순
result = df.groupby("부서")['연봉'].mean().sort_values(ascending=False)
print(result)

부서
개발     5750.0
디자인    5250.0
기획     4650.0
Name: 연봉, dtype: float64


In [ ]:
# 2가지 이상의 값에 대해서 그룹화 분석을 진행
df.groupby("부서")['연봉'].agg(['count','mean','max','min'])

count    mean   max   min
부서                            
개발       2  5750.0  6000  5500
기획       2  4650.0  4800  4500
디자인      2  5250.0  5300  5200

In [ ]:
df2 = pd.DataFrame({
    "부서": ["개발", "개발", "기획", "기획", "디자인", "디자인"],
    "직급": ["대리", "과장", "대리", "과장", "사원", "대리"],
    "연봉": [5500, 6200, 4700, 5000, 4200, 5100]
})

result = df2.groupby(["부서", "직급"])["연봉"].mean()
print(result)

부서   직급
개발   과장    6200.0
     대리    5500.0
기획   과장    5000.0
     대리    4700.0
디자인  대리    5100.0
     사원    4200.0
Name: 연봉, dtype: float64
